[package]
authors = ["Flix <felix.dommes@rwth-aachen.de>"]
categories = ["data-structures", "parser-implementations", "web-programming"]
description = "FHIR Software Development Kit. Library for interfacing with FHIR."
documentation = "https://docs.rs/fhir-sdk"
edition = "2021"
homepage = "https://github.com/FlixCoder/fhir-sdk"
keywords = ["FHIR", "JSON", "types"]
license = "MIT"
name = "fhir-sdk"
readme = "README.md"
repository = "https://github.com/FlixCoder/fhir-sdk"
version = "0.9.0"

[lints]
workspace = true

[features]
default = ["r5", "builders", "client", "docs"]
client = [
	"builders",
	"fhir-model/search-params",
	"dep:ordered-stream",
	"dep:pin-project-lite",
	"dep:async-trait",
	"dep:futures",
	"dep:reqwest",
	"dep:serde",
	"dep:serde_json",
	"dep:thiserror",
	"dep:tokio-retry",
	"dep:tracing",
	"dep:uuid",
]
builders = ["fhir-model/builders"]
stu3 = ["fhir-model/stu3"]
r4b = ["fhir-model/r4b"]
r5 = ["fhir-model/r5"]
docs = []

[dependencies]
async-trait = {version = "0.1.68", optional = true}
fhir-model = {path = "../fhir-model", version = "0.8.0", default-features = false}
futures = {version = "0.3.28", optional = true}
http = "1.1.0"
hyper = { version = "1.4.1", features = ["client", "http1"] }
hyper-util = { version = "0.1.6", features = ["client", "client-legacy", "http1"] }
ordered-stream = { git = "https://github.com/formelio/ordered-stream.git", branch = "master", optional = true }
pin-project-lite = {version = "0.2.14", optional = true}
reqwest = {version = "0.11.16", features = ["json"], optional = true}
serde = {version = "1.0.159", optional = true}
serde_json = {version = "1.0.95", optional = true}
thiserror = {version = "1.0.40", optional = true}
tokio-retry = {version = "0.3.0", optional = true}
tower = { version = "0.4.13", features = ["retry", "timeout"] }
tower-default-headers = "0.1.1"
tower-http = { version = "0.5.2", features = ["set-header"] }
tracing = {version = "0.1.4", optional = true}
uuid = {version = "1.4.1", features = ["v4"], optional = true}

[dev-dependencies]
eyre = "0.6.8"
once_cell = "1.18.0"
tokio = {version = "1.27.0", features = ["full"]}
tracing-subscriber = {version = "0.3.17", features = ["env-filter"]}

[package.metadata.docs.rs]
features = ["r5", "builders", "client", "docs"]
no-default-features = true
